defaults: &defaults
    relay_transport: lmtp:unix:private/lmtp
    relay_domains_file: relay_domains
    virtual_aliases_file: virtual_alias.cf
    virtual_mailboxes_file: virtual_mailbox.cf
    virtual_mailbox_domains_file: virtual_mailbox_domains.cf
    dovecot_auth_file: dovecot-sql.conf
    
development:
    <<: *defaults
    

test:
    <<: *defaults

production:
    <<: *defaults
    relay_transport:  dovecot: