defaults: &defaults
    relay_transport: lmtp:unix:/var/run/dovecot/lmtp
    export_relay_domains_file: relay_domains
    virtual_aliases_file: virtual_alias.cf
    relay_recipients_file: relay_recipients.cf
    relay_domains_file: relay_domains.cf
    dovecot_auth_file: dovecot-sql.conf
    
development:
    <<: *defaults
    

test:
    <<: *defaults

production:
    <<: *defaults
#    relay_transport:  dovecot: